parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     sf_asset
    database_user:     root
    database_password: ~

#    database_driver:   oci8
#    database_host:     192.168.1.101
#    database_port:     1521
#    database_name:     telecard
#    database_user:     gl
#    database_password: gl


    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
