unisoft_assets:
    resource: "@UnisoftAssetsBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    defaults:  { _locale: en }
    requirements:
        _locale: en|ar

#fos_js_routing:
#    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
#
#symfony_cmf_tree:
#    resource: .
#    type: 'symfony_cmf_tree'

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

#sonata_page_cache:
#    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
#    prefix: /
#    

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

#_sonata_admin:
#    resource: .
#    type: sonata_admin
#    prefix: /admin