jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
      connection: default
   
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Unisoft\AssetsBundle\Entity\User: sha1
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        administrators:
             entity: { class: UnisoftAssetsBundle:User}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/en/User/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /en/User/login_check
                login_path: /en/User/login
            logout:
                path:   /en/User/logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
