CREATE TABLE `MOVE`
  (
    `ID`       int,
    `ACCNO`    int,
    `COST1`    int,
    `DEBIT`    int,
    `CREDIT`   int,
    `DETAILS`  VARCHAR(500),
    `RESET`    int,
    `RESET_ID` int,
    `COST2`    int,
    `COST3`    int,
    `COST4`    int,
    `CHEK`     int,
    `CHEK_DATE` datetime,
    `BRANCH`          int,
    `FLAGE`           int,
    `PAYED`           int,
    `CREDIT1`         int,
    `DEBIT1`          int,
    `CURRENCY`        int,
    `CURR_RATE`       int,
    `INVNO_E`         int,
    `SMAN_E`          int,
    `FLAGE_CHECKED`   int,
    `INVOICE_CHECKED` int,
    `BANK_FLAG`       int,
    `CHECK_BOOK`      VARCHAR(35),
    `PAYED_RESET`     int,
    `PAYED_RESET_ID`  int,
    `PAYED_BRANCH`    int,
    `SER`             int,
    `RETURN_NO`       VARCHAR(30),
    `DEPOSIT_TYPE_ID` int,
    `DEPOSIT_BANK`    VARCHAR(100),
    `DEPOSIT_CHEQUE`  VARCHAR(100),
    `DEPOSIT_DATE` datetime,
    `COMPANY_ID`   int,
    `COMPANY_CODE` int,
    `ACCNAME`      VARCHAR(250),
    `ACCNAME_E`    VARCHAR(250),
    `ORIGINAL_ID`  int,
  PRIMARY KEY (`ID`, `RESET`, `RESET_ID`, `BRANCH`) ,
  CONSTRAINT `MOVE_MOVE1_FK` FOREIGN KEY (`RESET`, `RESET_ID`, `BRANCH`) REFERENCES `MOVE1`  (`RESET`, `RESET_ID`, `BRANCH`)
  )
ENGINE = InnoDB;
  
  
  --------------------------------------------
  
  
CREATE TABLE `MOVE1`
  (
    `BATCH` int,
    `VDATE` datetime,
    `RESET`    int,
    `SR`       int,
    `RESET_ID` int,
    `NAME_TO`  VARCHAR(100),
    `DETAILS`  VARCHAR(500),
    `CHEK`     int,
    `CHEK_DATE` datetime,
    `BRANCH`  int,
    `USER_NO` int,
    `TIME_STAMP` datetime,
    `CHEK_FLAGE`    int,
    `BANK`          VARCHAR(50),
    `TEMP1`         int,
    `TEMP2`         int,
    `DETAILS_1`     VARCHAR(500),
    `CURRENCY_TYPE` int,
    `CURRENCY_RATE` int,
    `POST_FLAGE`    int,
    `PRINT_USR`     int,
    `PRINT_DTM` datetime,
    `PRINT_NO`             int,
    `CHECK_BOOK`           VARCHAR(50),
    `PAID`                 int,
    `SITE_REQUISITION`     VARCHAR(20),
    `ADD_VOUCHER_USER`     VARCHAR(16),
    `LUPDATE_VOUCHER_USER` VARCHAR(16),
    `APPROVED`             int,
    `TYP`                  int,
    `INTER_COMPANY`        int,
    `POST_DATE` datetime,
    `POST_USER` VARCHAR(16),
    `APPROVED_DATE` datetime,
    `APPROVED_USER` VARCHAR(16),
    `POSTED`        int,
  PRIMARY KEY (`RESET`, `RESET_ID`, `BRANCH`)
  )
ENGINE = InnoDB;


-----------------------------------------------------
  
  
CREATE TABLE `GUIDE`
  (
    `ACCOUNT_ID`        int,
    `ACCNO_1`           VARCHAR(1),
    `ACCNO_2`           VARCHAR(8),
    `ACCNO_3`           VARCHAR(8),
    `ACCNO_4`           VARCHAR(8),
    `ACCNO_5`           VARCHAR(8),
    `ACCNO_6`           VARCHAR(8),
    `ACCNO_7`           VARCHAR(8),
    `ACCNO_8`           VARCHAR(8),
    `ACCNO_9`           VARCHAR(8),
    `ACCNO_10`          VARCHAR(8),
    `ACCNO`             VARCHAR(40),
    `ACCNAME`           VARCHAR(150),
    `ACCNAME_E`         VARCHAR(150),
    `OMIT`              int,
    `CASH`              int,
    `P_M`               VARCHAR(1),
    `TYP_BALANCE`       VARCHAR(1),
    `BANK`              int,
    `G`                 int,
    `G1`                int,
    `TEMP1`             int,
    `TEMP2`             int,
    `SORT`              int,
    `CUSTNO`            VARCHAR(20),
    `NO_2`              VARCHAR(5),
    `GROUP_ID`          int,
    `ACC_CATEGORY`      int,
    `ACC_INV`           int,
    `ACC_SALES`         int,
    `ACC_PURCHASE`      int,
    `ACC_PERSONAL`      int,
    `ACC_ASSEST`        int,
    `ACC_CURRENCY`      int,
    `IS_GL`             int,
    `ALIAS`             VARCHAR(50),
    `MASK_CODE`         VARCHAR(37),
    `ACCOUNT_LEVEL`     int,
    `ACCNO_FULL`        VARCHAR(40),
    `ISBREAKPOINTEVENT` VARCHAR(1),
    `BALANCE_CONTROL`   int,
    `DR_CR_PROP`        VARCHAR(1),
    `ACC_NATURE`        VARCHAR(1),
    `OLD_ACC`           VARCHAR(14),
    `OLD_ACC_FULL`      VARCHAR(14),
    `OLD_MASK_ACC`      VARCHAR(14),
    `ACC_TYP_BAL`       VARCHAR(1),
    `ACC_PERC`          int,
    `PARENT_CHILD`      int,
    `LEVELS_NO`         int,
    `LEVEL_2_LENGTH`    int,
    `LEVEL_3_LENGTH`    int,
    `LEVEL_4_LENGTH`    int,
    `LEVEL_5_LENGTH`    int,
    `LEVEL_6_LENGTH`    int,
    `LEVEL_7_LENGTH`    int,
    `LEVEL_8_LENGTH`    int,
    `LEVEL_9_LENGTH`    int,
    `LEVEL_10_LENGTH`   int,
    `DIRECT_CASH_FLOW`  int,
    `CATTYPES_ID`       int,
    `CATTYPES_SORT`     int,
    Primary Key (`ACCOUNT_ID`)
  );




-----------------------------------------------------



CREATE TABLE `CUSTOMERS2`
  (
    `ID`                 int NOT NULL,
    `NAME`               VARCHAR(150),
    `CAT1`               int,
    `CAT2`               int,
    `CADDRESS`           VARCHAR(100),
    `TEL1`               VARCHAR(100),
    `TEL2`               VARCHAR(100),
    `FAX`                VARCHAR(100),
    `CONTACT`            VARCHAR(100),
    `CREDIT_LIMIT_FLAGE` int,
    `CREDIT_LIMIT`       int,
    `CREDIT_DAYS`        int,
    `SALES_MAN`          int,
    `ACCNO`              VARCHAR(37),
    `DISCOUNT_CODE`      int,
    `NAME_E`             VARCHAR(150),
    `TEL4`               VARCHAR(100),
    `JOP`                VARCHAR(30),
    `NATIONAL`           VARCHAR(30),
    `BEGIN_DATE` datetime,
    `NOTES`      VARCHAR(4000),
    `CID`        VARCHAR(12),
    `SHOON`      VARCHAR(12),
    `TARKHES`    VARCHAR(12),
    `OP_BALANCE` int,
    `BALANCE`    int,
    `TEMP1`      int,
    `TEMP2`      int,
    `TEMP3`      int,
    `TEMP4`      int,
    `EMAIL`      VARCHAR(100),
    `WEB_PAGE`   VARCHAR(100),
    `TEMP_DATE` datetime,
    `TEMP_DATE2` datetime,
    `CREDIT_DAYS_FLAGE` int,
    `COST_CENTER`       int,
    `TO_DT` datetime,
    `DATE_FLAGE`                int,
    `DISCOUNT_RATIO`            int,
    `AREA_CODE`                 VARCHAR(20),
    `SECTOR`                    VARCHAR(20),
    `GADA`                      VARCHAR(20),
    `STREET`                    VARCHAR(50),
    `HOUSE`                     VARCHAR(50),
    `FLAT`                      VARCHAR(20),
    `FLOOR`                     VARCHAR(20),
    `ISBRANCH`                  int,
    `PCENTER`                   int,
    `INST_ACCEPTLESSTHANMINVAL` int,
    `OB_BALANCE_F`              int,
    `OB_BALANCE_CURR`           int,
    `CUST_MANID`                VARCHAR(20),
    `SECTION`                   int,
    `IS_STOP`                   int,
    `STOP_DATE` 		datetime,
    `STOP_REASON` 		VARCHAR(150),
    `STOP_USER`   		VARCHAR(100),
    `ROUTE`       int,
    `ACCOUNT_ID`  int,
  PRIMARY KEY (`ID`) 
  );
